modLoader="javafml"
# Forge 1.20.1 のローダー（47系）以上
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="pbj_iris_shadowfix"
version="${file.jarVersion}"
displayName="PBJ Iris Shadow Fix"
description="Disable PointBlank's Iris shadow hook to avoid crash."
mixins = ["pbjshadowfix.mixins.json"]
# 依存セクションは一切置かない（Forge/PointBlank/Oculus を要求しない）
