name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle (no cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8
          cache-disabled: true     # ← キャッシュ無効化

      - name: Show versions
        run: |
          gradle -v
          java -version

      - name: Build with Gradle
        run: gradle build --no-daemon --stacktrace --info

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: pbj-iris-shadowfix-jar
          path: build/libs/*.jar
